# Module 1 - Session 4 (25.06.2026)

## Recap

### Strings, Lists, and loops

We will start by defining a list, with multiple types (int, str, float, bool) and append a complex variable at the end.

In [78]:
example = [1, 2, 3, 4, "temperature", "operator", "pressure", 3.0, 4.5, -3.0, True, False]

In [71]:
print("My list is: ", example)

My list is:  [1, 2, 3, 4, 'temperature', 'operator', 'pressure', 3.0, 4.5, -3.0, True, False]


In [72]:
print(f"My list is: {example}")  # f-string type of printing

My list is: [1, 2, 3, 4, 'temperature', 'operator', 'pressure', 3.0, 4.5, -3.0, True, False]


In [73]:
text = "my text is this"
print(f"I operated with something and the final string is: '{text}'")

I operated with something and the final string is: 'my text is this'


In [74]:
example[0], example[2], example[4], example[-1]

(1, 3, 'temperature', False)

In [75]:
text[0], text[1], text[3], text[-1]  # texts are also list of characters (each element is a character)

('m', 'y', 't', 's')

In [79]:
example.append(3.0 + 4j)  # adding another element to the end of the list
print(example)

[1, 2, 3, 4, 'temperature', 'operator', 'pressure', 3.0, 4.5, -3.0, True, False, (3+4j)]


Exercise 1 - From the list `example`, take out all the string and boolean elements, and create a new list with only integers, floats, and complex numbers

In [80]:
for element in example:
    # we are going one by one through example[0], example[1], ..., example[-1]
    print(element)

1
2
3
4
temperature
operator
pressure
3.0
4.5
-3.0
True
False
(3+4j)


In [83]:
for element in example:
    print(element, type(element))  # printing each element and their types

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
temperature <class 'str'>
operator <class 'str'>
pressure <class 'str'>
3.0 <class 'float'>
4.5 <class 'float'>
-3.0 <class 'float'>
True <class 'bool'>
False <class 'bool'>
(3+4j) <class 'complex'>


In [87]:
# Operators
# >=, >, <, <=, ==, !=, % 
3 < 2

False

In [90]:
for element in example:
    if type(element) == str or type(element) == bool:
        continue  # or break if we want to go out fully from the loop (see next cell)
    else:
        print(element)

1
2
3
4
3.0
4.5
-3.0
(3+4j)


In [91]:
for element in example:
    if type(element) == str or type(element) == bool:
        break
    else:
        print(element)

1
2
3
4


In [94]:
example  # but `example` didn't change yet, we just printed the elements in the loop without str and without bool

[1,
 2,
 3,
 4,
 'temperature',
 'operator',
 'pressure',
 3.0,
 4.5,
 -3.0,
 True,
 False,
 (3+4j)]

In [ ]:
new_example = []  # important!
for element in example:
    if type(element) == str or type(element) == bool:
        continue
    else:
        new_example.append(element)
print(new_example)

[1, 2, 3, 4, 3.0, 4.5, -3.0, (3+4j)]


In [97]:
new_example = []
for element in example:
    if isinstance(element, str) or isinstance(element, bool):  # better for comparing classes types
        continue
    else:
        new_example.append(element)
print(new_example)

[1, 2, 3, 4, 3.0, 4.5, -3.0, (3+4j)]


Exercise 2 - Given a list of integer numbers [1, 2, 3, 202, 344, 33, 90, 2026], print only the even numbers (use element % 2 == 0). Do the same but for odd numbers (search online the operator for this, which is not `==`)

In [98]:
number_list = [1, 2, 3, 202, 344, 33, 90, 2026]
for element in number_list:
    if element % 2 == 0:  # even number
        print("Even number: ", element)
    else:
        print("Odd number: ", element)

Odd number:  1
Even number:  2
Odd number:  3
Even number:  202
Even number:  344
Odd number:  33
Even number:  90
Even number:  2026


In [99]:
for element in number_list:
    if element % 2 == 0:  # even number
        print("Even number: ", element)
    elif element % 2 != 0:  # odd number
        print("Odd number: ", element)
    # elif ...
    # elif ...
    else:  # typically a fallback in case none of the other "if" conditions are satisfied
        print("Numbers are always odd or even, but maybe the universe is broken and here we are: ", element)

Odd number:  1
Even number:  2
Odd number:  3
Even number:  202
Even number:  344
Odd number:  33
Even number:  90
Even number:  2026


Exercise 3 - (Error handling introduction) Define a list [1, 2, 3, 202, 344, 33, 90, 2026, "temperature"] and repeat the example before being careful of the type

In [100]:
error_list = ["pressure", 1, 2, 3, 202, 344, 33, 90, 2026, "temperature"]
for element in error_list:
    if isinstance(element, int):
        if element % 2 == 0:  # even number
            print("Even number: ", element)
        elif element % 2 != 0:  # odd number
           print("Odd number: ", element)
    else:
        print("ERROR! The element is not an integer, hence I cannot calculate the modulo")

ERROR! The element is not an integer, hence I cannot calculate the modulo
Odd number:  1
Even number:  2
Odd number:  3
Even number:  202
Even number:  344
Odd number:  33
Even number:  90
Even number:  2026
ERROR! The element is not an integer, hence I cannot calculate the modulo


### Enumerate and lists

In [102]:
for index, element in enumerate(example):
    print(index, element, example[index])

0 1 1
1 2 2
2 3 3
3 4 4
4 temperature temperature
5 operator operator
6 pressure pressure
7 3.0 3.0
8 4.5 4.5
9 -3.0 -3.0
10 True True
11 False False
12 (3+4j) (3+4j)


In [103]:
len(example)  # how many elements does the list have

13

In [104]:
text = "ajsnfiusnagiunaisdugbiaudbgiaubodiugbagiub yasf yagufdoygaou ysgduya  afuh"
len(text)  # how many characters does the text have

74

In [105]:
example_pruning = [
    ["in eV", "in meters"],  # index = 0
    [2, 3],  # index = 1
    ["in J", "in inches"],  # index = 2
    [0.00000002, 6],  # index = 3
    ["in Ha", "in cm"],  # index = 4
    [10, 300],  # index = 5
]
for index, element in enumerate(example_pruning):
    if index % 2 == 0:  # only taking odd elements in the list
        continue
    else:
        print("Values: ", element)

Values:  [2, 3]
Values:  [2e-08, 6]
Values:  [10, 300]


## Dictionaries and nesting

In [106]:
example_dict = {
    "key1": 10,
    "key2": "another string",
    "key3": 3 + 3j,
    "key4": [1, 2, 3],
    "key5": {
        "inside_key1": 22,
        "inside_key2": 39.0,
        "inside_key3": {
            "inside_inside_key1": "temperature"
        }
    }
}

In [107]:
for key, value in example_dict.items():
    print(key, value)

key1 10
key2 another string
key3 (3+3j)
key4 [1, 2, 3]
key5 {'inside_key1': 22, 'inside_key2': 39.0, 'inside_key3': {'inside_inside_key1': 'temperature'}}


In [108]:
for key, value in example_dict.items():
    if isinstance(value, dict):
        for subkey, subvalue in value.items():  # this can be nested as many times as nested dicts are
            print(subkey, subvalue)
    else:
        print(key, value)

key1 10
key2 another string
key3 (3+3j)
key4 [1, 2, 3]
inside_key1 22
inside_key2 39.0
inside_key3 {'inside_inside_key1': 'temperature'}


Exercise 4 - Create a dictionary to describe your persona

In [109]:
person = {
    "name": "Max",
    "family name": "Mustermann",
    "home address": {
        "street": "xxxx",
        "street no": 1,
        "ZIP": 11111,
        "city": "xxxx",
        "country": "Germany",
    },
    "nationality": "Germany",
}

In [110]:
person["family name"]

'Mustermann'

In [112]:
person["Family name"]  # key not present in the dictionary `person`

KeyError: 'Family name'

In [114]:
person["home address"]["country"]

'Germany'

In [121]:
person_2 = {
    "name": "Eva",
    "family name": "Mustermann",
    "home address": {
        "street": "xxxx",
        "street no": 1,
        "ZIP": 11111,
        "city": "xxxx",
        "country": "Germany",
    },
    "nationality": "Germany",
}

person["wife"] = person_2
person

{'name': 'Max',
 'family name': 'Mustermann',
 'home address': {'street': 'xxxx',
  'street no': 1,
  'ZIP': 11111,
  'city': 'xxxx',
  'country': 'Germany'},
 'nationality': 'Germany',
 'wife': {'name': 'Eva',
  'family name': 'Mustermann',
  'home address': {'street': 'xxxx',
   'street no': 1,
   'ZIP': 11111,
   'city': 'xxxx',
   'country': 'Germany'},
  'nationality': 'Germany'}}

In [122]:
keys_list = ["name", "family name", "nationality"]
data = []
for key in keys_list:
    data.append(person[key])
print(data)

['Max', 'Mustermann', 'Germany']


In [123]:
person.pop("wife")

{'name': 'Eva',
 'family name': 'Mustermann',
 'home address': {'street': 'xxxx',
  'street no': 1,
  'ZIP': 11111,
  'city': 'xxxx',
  'country': 'Germany'},
 'nationality': 'Germany'}

In [124]:
person == person_2

False

In [125]:
instruments = [
    {"name": "D8D", "location": "UE"},
    {"name": "D6D", "location": "UE"},
    {"name": "D8A", "location": "UE"},
]
instrument_register_new_one = {"name": "Dd", "location": "AH"}
for instrument in instruments:
    if instrument_register_new_one == instrument:
        print("HEY! The instrument is already registered in the database, do not duplicate it!")
        # going somewhere else
print("Storing new instrument in the database")

Storing new instrument in the database
